services:
  - type: web
    name: nexa-api
    env: python
    plan: free
    buildCommand: pip install -U pip && pip install -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu
    startCommand: bash start.sh
